[tool.flake8]
ignore = ["C901", "D100", "D101", "D102", "D103", "W503", "W504"]
exclude = ['.eggs', '.git', '.tox', '.venv', '.build', 'build', 'report']
max-line-length = 99
max-complexity = 10

[tool.black]
line-length = 99
exclude = '''
/(
    | .eggs
    | .git
    | .tox
    | .venv
    | .build
    | build
    | report
)/
'''

[tool.isort]
profile = "black"
skip_glob = [
  ".eggs",
  ".git",
  ".tox",
  ".venv",
  ".build",
  "build",
  "report"
]

[tool.pylint]
max-line-length = 99
ignore = ['.eggs', '.git', '.tox', '.venv', '.build', 'report', 'tests']

[tool.mypy]
warn_unused_ignores = true
warn_unused_configs = true
warn_unreachable = true
disallow_untyped_defs = true
exclude = ['.eggs', '.git', '.tox', '.venv', '.build', 'report', 'tests']

## Ignore unsupported imports
[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["setuptools"]

[tool.coverage.run]
relative_files = true
source = ["."]
omit = ["docs/**", "lib/**", "snap/**", "build/**", "setup.py"]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.coverage.html]
directory = "tests/unit/report/html"

[tool.coverage.xml]
output = "tests/unit/report/coverage.xml"
