#!/bin/sh -e

cat <<EOF
Tailscale has been updated,
but the previous revision of the Tailscale service is still running.

Please manually restart the service when convenient.
WARNING: this may cause temporary network disruptions as the service restarts.

$ sudo snap restart tailscale
EOF
